/* BOOK testtest */
CREATE TABLE TABLE (
	COL NUMBER(3) NOT NULL, /* bno */
	COL2 VARCHAR2(20), /* bname */
	COL3 VARCHAR2(4000), /* bdesc */
	COL4 NUMBER(10) /* bprice */
);

/* MEM */
CREATE TABLE TABLE2 (
	COL NUMBER(20) NOT NULL, /* MEMID */
	COL2 VARCHAR2(20), /* MEMNAME */
	COL3 VARCHAR2(20) /* MEMADDR */
);

/* BORDER */
CREATE TABLE TABLE3 (
	COL5 NUMBER(3) NOT NULL, /* bno */
	COL3 NUMBER(20) NOT NULL, /* MEMID */
	COL NUMBER(4), /* ONO */
	COL2 NUMBER(3), /* BNO */
	COL4 NUMBER(2) /* OQTY */
);